USE [master]
GO
/****** Object:  Database pega    Script Date: 28/09/2023 06:15:43 ******/
CREATE DATABASE pega
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pega', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pega.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pega_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pega_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE pega SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC pega.[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE pega SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE pega SET ANSI_NULLS OFF 
GO
ALTER DATABASE pega SET ANSI_PADDING OFF 
GO
ALTER DATABASE pega SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE pega SET ARITHABORT OFF 
GO
ALTER DATABASE pega SET AUTO_CLOSE OFF 
GO
ALTER DATABASE pega SET AUTO_SHRINK OFF 
GO
ALTER DATABASE pega SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE pega SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE pega SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE pega SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE pega SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE pega SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE pega SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE pega SET  DISABLE_BROKER 
GO
ALTER DATABASE pega SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE pega SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE pega SET TRUSTWORTHY OFF 
GO
ALTER DATABASE pega SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE pega SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE pega SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE pega SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE pega SET RECOVERY SIMPLE 
GO
ALTER DATABASE pega SET  MULTI_USER 
GO
ALTER DATABASE pega SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE pega SET DB_CHAINING OFF 
GO
ALTER DATABASE pega SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE pega SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE pega SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE pega SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE pega SET QUERY_STORE = OFF
GO
USE pega
GO
/****** Object:  Table [dbo].[base_dados]    Script Date: 28/09/2023 06:15:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[base_dados](
	[ID] [nvarchar](50) primary key NOT NULL,
	[Aluno] [nvarchar](50) NOT NULL,
	[Matricula] [nvarchar](50) NOT NULL,
	[Turma] [nvarchar](50) NOT NULL,
	[CPF] [float] NOT NULL,
	[Nascimento] [datetime2](7) NOT NULL,
	[PalavraChave] [nvarchar](1) NULL,
	[Senha] [nvarchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cursos]    Script Date: 28/09/2023 06:15:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cursos](
	[ID] [nvarchar](50) primary key,
	[Nome] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[disciplinas]    Script Date: 28/09/2023 06:15:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[disciplinas](
	[ID] [nvarchar](50) NOT NULL,
	[Nome] [nvarchar](100) NOT NULL,
	[Curso] [nvarchar](50) references [dbo].[cursos](ID),
	[Periodo] [nvarchar](50) NOT NULL,
	[Pre_requisito] [nvarchar](50) NULL,
	[Docente] [nvarchar](50) references [dbo].[docentes](ID) NOT NULL,
 CONSTRAINT [PK_disciplinas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[docentes]    Script Date: 28/09/2023 06:15:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[docentes](
	[ID] [nvarchar](50) NOT NULL,
	[Nome] [nvarchar](50) NOT NULL,
	[CPF] [float] NOT NULL,
	[Matricula] [nvarchar](50) NOT NULL,
	[Nascimento] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_docentes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[status](
	ID [nvarchar](50) primary key,
	Tipo [nvarchar](50) NOT NULL
)

/****** Object:  Table [dbo].[notas]    Script Date: 28/09/2023 06:15:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notas](
	[ID] [nvarchar](50) NOT NULL,
	[IdAluno] [nvarchar](50) references [dbo].[base_dados](ID) NOT NULL,
	[Disciplina] [nvarchar](50) NOT NULL,
	[AV1] [nvarchar](50) NULL,
	[AV2] [nvarchar](50) NULL,
	[Faltas] [nvarchar](50) NOT NULL,
	[Status] [nvarchar](50) references [dbo].[status](ID) NOT NULL,
 CONSTRAINT [PK_notas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[turmas]    Script Date: 28/09/2023 06:15:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[turmas](
	[ID] [nvarchar](50) NOT NULL,
	[Codigo_Turma] [nvarchar](50) NOT NULL,
	[Curso] [nvarchar](50) references [dbo].[cursos](ID) NOT NULL,
	[Ano] [int] NOT NULL,
	[Semestre] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_turmas] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE pega SET  READ_WRITE 
GO
