//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopPR
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlunoApresentacao
    {
        public int id { get; set; }
        public Nullable<int> idApresentacao { get; set; }
        public Nullable<int> idAluno { get; set; }
    
        public virtual Alunos Alunos { get; set; }
        public virtual Apresentacao Apresentacao { get; set; }
    }
}
