//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopPR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DesktopPREntities1 : DbContext
    {
        public DesktopPREntities1()
            : base("name=DesktopPREntities1")
        {
            Database.SetInitializer(
                    new CreateDatabaseIfNotExists<DesktopPREntities1>()
                );
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlunoApresentacao> AlunoApresentacao { get; set; }
        public virtual DbSet<AlunoExcluido> AlunoExcluido { get; set; }
        public virtual DbSet<Alunos> Alunos { get; set; }
        public virtual DbSet<Apresentacao> Apresentacao { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
